project_id = "mkozkrpyjehtfqsfnymr"

[functions.create-lead]
verify_jwt = false

[functions.track-page-view]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.track-whatsapp-click]
verify_jwt = false

[functions.reset-analytics]
verify_jwt = false

[functions.manage-users]
verify_jwt = false
